<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useRoute } from 'vue-router'
import { createMeetingService, type AnalysisMode, type ReviewDetail, type ReviewDraft } from '../services/meetingService'
import type { UserAccount } from '../services/authService'
import { analysisStatusLabel } from '../utils/labels'

const props = defineProps<{ token: string; user: UserAccount }>()
const route = useRoute(); const service = createMeetingService(props.token)
const detail = ref<ReviewDetail | null>(null); const loading = ref(true); const error = ref(''); const notice = ref(''); const reason = ref(''); const showReason = ref(false); const saving = ref(false); const reanalysisMode = ref<AnalysisMode>('llm')
const canManage = computed(() => props.user.role === 'manager')
const draft = ref<ReviewDraft>({ summary: '', decisions: [], tasks: [], risks: [] })
function addTask() { draft.value.tasks.push({ title: '', priority: 'medium' }) }
function removeTask(index: number) { draft.value.tasks.splice(index, 1) }
function addDecision() { draft.value.decisions.push('') }
function removeDecision(index: number) { draft.value.decisions.splice(index, 1) }
function addRisk() { draft.value.risks.push({ title: '', level: 'medium' }) }
function removeRisk(index: number) { draft.value.risks.splice(index, 1) }
async function load() { loading.value = true; try { detail.value = await service.getReviewDetail(String(route.params.id)); draft.value = JSON.parse(JSON.stringify(detail.value.draft || detail.value.analysis?.result || draft.value)) } catch (e) { error.value = e instanceof Error ? e.message : '审核详情加载失败' } finally { loading.value = false } }
async function saveDraft() { if (!detail.value || !canManage.value) return; saving.value = true; try { await service.saveReviewDraft(detail.value.analysis.id, draft.value); notice.value = '草稿已保存' } catch (e) { notice.value = e instanceof Error ? e.message : '保存失败' } finally { saving.value = false } }
function validateReason() { return reason.value.trim().length >= 1 && reason.value.trim().length <= 500 }
async function submit(approved: boolean, ids = [detail.value?.analysis?.id].filter(Boolean) as string[]) { if (!canManage.value || !ids.length) return; if (!approved && !validateReason()) { showReason.value = true; return } if (!approved && !window.confirm(`确认驳回 ${ids.length} 条分析？`)) return; try { if (ids.length > 1) await service.reviewBatch(ids, approved, reason.value); else await service.review(ids[0], approved, reason.value); notice.value = approved ? '审核已通过' : '已驳回并记录原因'; showReason.value = false; reason.value = ''; await load() } catch (e) { notice.value = e instanceof Error ? e.message : '审核失败' } }
async function reanalyze() { if (detail.value && canManage.value && window.confirm('确认重新分析？')) { await service.reanalyze(detail.value.analysis.id, reanalysisMode.value); notice.value = '已重新发起分析'; await load() } }
onMounted(load)
</script>

<template>
  <section class="page-section review-detail-page">
    <div v-if="loading" class="panel empty-cell">正在加载审核详情…</div><div v-else-if="error" class="panel empty-cell">{{ error }} <button class="small-button" @click="load">重试</button></div>
    <template v-else-if="detail">
      <div class="review-header"><div><p class="eyebrow">AI REVIEW DETAIL</p><h2>{{ detail.meeting.title }}</h2><p class="muted">分析状态：<span class="tag" :class="analysisStatusLabel(detail.analysis.status).tone">{{ analysisStatusLabel(detail.analysis.status).label }}</span></p></div><div v-if="canManage" class="page-actions"><template v-if="['failed', 'rejected'].includes(detail.analysis.status)"><label class="modal-field"><span>重新分析模式</span><select v-model="reanalysisMode" aria-label="重新分析模式"><option value="manual">人工审核</option><option value="llm">LLM</option><option value="rag">RAG</option><option value="agent">智能体</option></select></label><button class="secondary-button" @click="reanalyze">重新分析</button></template><template v-else-if="detail.analysis.status === 'pending'"><button class="primary-button" @click="submit(true)">通过</button><button class="secondary-button" @click="showReason = true">驳回</button></template></div></div>
      <p v-if="notice" class="meeting-notice muted">{{ notice }}</p>
      <div class="detail-grid"><div><span>分析模式</span><strong>{{ detail.analysis.mode }}</strong></div><div><span>模型调用</span><strong>{{ detail.analysis.modelCallCount }} 次</strong></div><div><span>执行耗时</span><strong>{{ detail.analysis.durationMs }} ms</strong></div><div><span>检索状态</span><strong>{{ detail.analysis.executionMetadata?.retrievalStatus ?? '-' }}</strong></div></div>
      <p v-if="detail.analysis.executionMetadata?.retrievalStatus === 'not_configured'" class="meeting-notice muted">检索未配置</p>
      <section v-if="detail.analysis.executionMetadata?.retrievalStatus === 'completed'" class="panel retrieval-evidence"><div class="panel-heading"><h3>检索依据</h3><small>{{ detail.analysis.executionMetadata?.retrievalDurationMs ?? 0 }} ms · {{ detail.analysis.executionMetadata?.retrievalHitCount ?? 0 }} 条命中</small></div><div v-if="detail.analysis.executionMetadata?.retrievalSources?.length" class="evidence-list"><div v-for="source in detail.analysis.executionMetadata?.retrievalSources" :key="`${source.meetingId}-${source.versionId}-${source.chunkIndex}`" class="evidence-snippet"><strong>会议 {{ source.meetingId }}</strong><small>版本 {{ source.versionId }} · 分块 {{ source.chunkIndex }} · 相似度 {{ source.score }}</small></div></div><div v-else class="empty-cell">未命中可用的项目历史片段。</div></section>
      <div class="analysis-grid"><article class="panel evidence-panel"><div class="panel-heading"><h3>脱敏纪要与证据</h3></div><pre class="evidence-text">{{ detail.meeting.desensitizedContent || detail.meeting.content || '暂无内容' }}</pre><div class="evidence-list"><div v-for="(evidence, index) in detail.evidence" :key="index" class="evidence-snippet"><span class="tag blue">证据 {{ index + 1 }}</span><p>{{ evidence.snippet }}</p><small>位置 {{ evidence.start }}-{{ evidence.end }}</small></div></div></article>
        <article class="panel detail-panel"><div class="panel-heading"><h3>分析结果与草稿</h3><button v-if="canManage" class="small-button" :disabled="saving" @click="saveDraft">{{ saving ? '保存中…' : '保存草稿' }}</button></div><label class="modal-field"><span>摘要</span><textarea v-model="draft.summary" rows="4" :readonly="!canManage" /></label><div class="draft-section-head"><div class="section-label">决策</div><button v-if="canManage" class="icon-button" title="添加决策" @click="addDecision"><span aria-hidden="true">+</span></button></div><div v-for="(_, index) in draft.decisions" :key="`decision-${index}`" class="draft-row"><input v-model="draft.decisions[index]" :readonly="!canManage" placeholder="决策内容" /><button v-if="canManage" class="icon-button" title="删除决策" @click="removeDecision(index)">×</button></div><div v-if="!draft.decisions.length" class="empty-cell">暂无决策</div><div class="draft-section-head"><div class="section-label">候选任务</div><button v-if="canManage" class="icon-button" title="添加任务" @click="addTask"><span aria-hidden="true">+</span></button></div><div v-for="(task, index) in draft.tasks" :key="`task-${index}`" class="draft-item"><div class="draft-row"><input v-model="task.title" :readonly="!canManage" placeholder="任务标题" /><select v-model="task.priority" :disabled="!canManage"><option value="urgent">urgent</option><option value="high">high</option><option value="medium">medium</option><option value="low">low</option></select><button v-if="canManage" class="icon-button" title="删除任务" @click="removeTask(index)">×</button></div><div class="draft-row"><input v-model="task.owner_email" :readonly="!canManage" placeholder="负责人邮箱" /><input v-model="task.due_date" type="date" :readonly="!canManage" /><input v-model="task.description" :readonly="!canManage" placeholder="任务说明" /></div></div><div v-if="!draft.tasks.length" class="empty-cell">暂无候选任务，可保存为无任务会议</div><div class="draft-section-head"><div class="section-label">风险</div><button v-if="canManage" class="icon-button" title="添加风险" @click="addRisk"><span aria-hidden="true">+</span></button></div><div v-for="(risk, index) in draft.risks" :key="`risk-${index}`" class="draft-item"><div class="draft-row"><input v-model="risk.title" :readonly="!canManage" placeholder="风险标题" /><select v-model="risk.level" :disabled="!canManage"><option value="high">high</option><option value="medium">medium</option><option value="low">low</option></select><button v-if="canManage" class="icon-button" title="删除风险" @click="removeRisk(index)">×</button></div><input v-model="risk.description" :readonly="!canManage" placeholder="风险说明" /></div><div v-if="!draft.risks.length" class="empty-cell">暂无风险</div></article></div>
      <div v-if="showReason" class="modal-backdrop" @click.self="showReason = false"><div class="modal"><div class="modal-head"><h3>填写驳回原因</h3><button class="icon-button" @click="showReason = false">×</button></div><label class="modal-field"><span>原因（1-500字）</span><textarea v-model="reason" rows="5" maxlength="500" placeholder="请说明需要修改的内容" /></label><p v-if="reason && !validateReason()" class="muted">驳回原因长度必须为 1-500 字</p><div class="modal-actions"><button class="secondary-button" @click="showReason = false">取消</button><button class="primary-button" :disabled="!validateReason()" @click="submit(false)">确认驳回</button></div></div></div>
    </template>
  </section>
</template>
