const auditActionLabels: Record<string, string> = {
  'analysis.approved': '分析结果已通过',
  'analysis.assignment_enriched': '分析任务分配已补充',
  'analysis.draft_saved': '分析草稿已保存',
  'analysis.reanalysis_failed': '分析重新执行失败',
  'analysis.reanalyzed': '分析已重新执行',
  'analysis.rejected': '分析结果已驳回',
  'desensitization_rule.created': '脱敏规则已创建',
  'desensitization_rule.deleted': '脱敏规则已删除',
  'desensitization_rule.updated': '脱敏规则已更新',
  'export.requested': '数据导出已请求',
  'meeting.analysis_failed': '会议分析失败',
  'meeting.analyzed': '会议已分析',
  'meeting.created': '会议已创建',
  'meeting.version_restored': '会议版本已恢复',
  'notification.sent': '通知已发送',
  'notifications.demo_generated': '演示通知已生成',
  'project.archived': '项目已归档',
  'project.created': '项目已创建',
  'project.deleted': '项目已删除',
  'project.member_added': '项目成员已添加',
  'project.member_removed': '项目成员已移除',
  'project.member_role_updated': '项目成员角色已更新',
  'project.rag_index_synced': '项目知识库索引已同步',
  'project.restored': '项目已恢复',
  'project.tag_created': '项目标签已创建',
  'project.tag_deleted': '项目标签已删除',
  'project.tag_linked': '项目标签已关联',
  'project.tag_unlinked': '项目标签已取消关联',
  'project.tag_updated': '项目标签已更新',
  'project.updated': '项目已更新',
  'risk.resolved': '风险已解决',
  'system_settings.updated': '系统设置已更新',
  'task.closed': '任务已关闭',
  'task.created': '任务已创建',
  'task.feedback_created': '任务反馈已创建',
  'task.note_created': '任务备注已创建',
  'task.reminder_sent': '任务提醒已发送',
  'task.reopened': '任务已重新打开',
  'task.updated': '任务已更新',
  'user.created': '账号已创建',
  'user.password_reset': '账号密码已重置',
  'user.updated': '账号已更新',
}

export function auditActionLabel(action: unknown): string {
  const value = String(action ?? '')
  return auditActionLabels[value] ?? value
}
